# Generated by Django 3.2.13 on 2023-02-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au_name', models.CharField(max_length=30, verbose_name='姓名')),
                ('au_account', models.CharField(max_length=30, verbose_name='账号')),
                ('au_pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('au_role', models.IntegerField(default=2, verbose_name='角色')),
                ('au_tel', models.CharField(max_length=30, verbose_name='电话')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
            },
        ),
        migrations.CreateModel(
            name='Customers_suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_attitude', models.CharField(max_length=20, verbose_name='供应商/客户')),
                ('cs_postCode', models.IntegerField(default=0, verbose_name='邮编')),
                ('cs_address', models.CharField(max_length=50, verbose_name='地址')),
                ('cs_tel', models.CharField(max_length=20, verbose_name='电话')),
                ('cs_unit', models.CharField(max_length=30, verbose_name='单位')),
                ('cs_name', models.CharField(max_length=30, verbose_name='联系人')),
            ],
            options={
                'verbose_name': '供应商和客户',
                'verbose_name_plural': '供应商和客户',
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30, verbose_name='药品名')),
                ('medicine_manufacturers', models.CharField(max_length=30, verbose_name='生产商')),
                ('medicine_trademark', models.CharField(max_length=30, verbose_name='品牌')),
                ('medicine_production_address', models.CharField(max_length=50, verbose_name='生产地址')),
                ('medicine_code', models.CharField(max_length=30, verbose_name='条码号')),
                ('medicine_specification', models.CharField(max_length=20, verbose_name='规格')),
                ('medicine_purchase', models.FloatField(default=0, verbose_name='进货价')),
                ('medicine_selling', models.FloatField(default=0, verbose_name='出售价')),
                ('medicine_quantity', models.IntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
            },
        ),
        migrations.CreateModel(
            name='Warehouse_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wr_in_out', models.CharField(max_length=20, verbose_name='入库/出库')),
                ('wr_quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('wr_cs_name', models.CharField(max_length=20, verbose_name='供应商/客户')),
                ('wr_admin_name', models.CharField(max_length=20, verbose_name='记录管理员')),
                ('wr_medicine_name', models.CharField(max_length=20, verbose_name='药品名')),
                ('wr_in_out_time', models.DateField(auto_now=True, verbose_name='时间')),
                ('wr_amount', models.FloatField(default=0, verbose_name='金额')),
            ],
            options={
                'verbose_name': '出入库记录',
                'verbose_name_plural': '出入库记录',
            },
        ),
    ]
